# Generated by Django 4.2.2 on 2023-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('expert', 'Expert'), ('admin', 'Admin'), ('initator', 'Initator'), ('project office', 'Project Office')], default='админ', max_length=14, verbose_name='Роль'),
        ),
    ]
