# Generated by Django 4.2.2 on 2023-07-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('expert', 'Expert'), ('admin', 'Admin'), ('initializer', 'Initializer'), ('projectOffice', 'Projectoffice')], default='admin', max_length=13, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
