# Generated by Django 4.2.2 on 2023-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(db_index=True, default='1', editable=False, unique=True, verbose_name='Токен'),
        ),
    ]
