# Generated by Django 4.2.2 on 2023-07-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('expert', 'Expert'), ('admin', 'Admin'), ('initializer', 'Initializer'), ('projectOffice', 'Projectoffice')], default='admin', max_length=13, verbose_name='Роль'),
        ),
    ]
