# Generated by Django 4.2.2 on 2023-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0002_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
