# Generated by Django 4.2.2 on 2023-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0003_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(db_index=True, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
