# Generated by Django 4.2.2 on 2023-07-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название идей')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('на согласовании', 'On Approval'), ('на утверждении', 'On Adoption'), ('утверждено', 'Adopted')], default='на согласовании', max_length=15)),
                ('rating', models.FloatField(default=0.0)),
                ('risk', models.FloatField(default=0.0)),
                ('initator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
        ),
    ]
