# Generated by Django 4.2.2 on 2023-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название идей')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('on approval', 'On Approval'), ('on adoption', 'On Adoption'), ('adopted', 'Adopted')], default='on approval', max_length=15)),
                ('rating', models.FloatField(default=0.0)),
                ('risk', models.FloatField(default=0.0)),
            ],
        ),
    ]
