# Generated by Django 4.2.2 on 2023-07-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IdeasManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='initator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='token', verbose_name='Инициатор'),
        ),
    ]
