# Generated by Django 4.2.2 on 2023-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeasManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('на согласовании', 'On Approval'), ('на утверждении', 'On Adoption'), ('утверждено', 'Adopted')], default='on approval', max_length=15),
        ),
    ]
