# Generated by Django 4.2.2 on 2023-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeasManagerApp', '0002_alter_idea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('на согласовании', 'On Approval'), ('на утверждении', 'On Adoption'), ('утверждено', 'Adopted')], default='на согласовании', max_length=15),
        ),
    ]
